# Generated by Django 4.2.4 on 2023-08-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id_trb', models.AutoField(primary_key=True, serialize=False)),
                ('intitulé_trb', models.CharField(max_length=200)),
                ('resp_trb', models.CharField(max_length=200)),
            ],
        ),
    ]
