# Generated by Django 4.2.4 on 2023-08-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='id_trb',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
