# Generated by Django 4.2.4 on 2023-08-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tribe_id_trb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribe',
            old_name='intitulé_trb',
            new_name='intitule_trb',
        ),
    ]
