# Generated by Django 4.2.4 on 2023-08-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_intitulé_trb_tribe_intitule_trb'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacation',
            fields=[
                ('id_vac', models.AutoField(primary_key=True, serialize=False)),
                ('emp_vac', models.CharField(max_length=200)),
                ('emp_vac_post', models.CharField(max_length=200)),
                ('start_vac', models.DateField()),
                ('end_vac', models.DateField()),
                ('nbr_jour_vac', models.IntegerField()),
            ],
        ),
    ]
