# Generated by Django 4.2.4 on 2023-09-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vacation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='emp_vac',
            new_name='approbateur_vac',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='nbr_jour_vac',
            new_name='duration_vac',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='emp_vac_post',
        ),
        migrations.AddField(
            model_name='vacation',
            name='id_emp_vac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='reason_vac',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='type_vac',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
