# Generated by Django 4.2.4 on 2023-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_emp_vac_vacation_approbateur_vac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='poste',
            field=models.TextField(null=True),
        ),
    ]
