# Generated by Django 4.2.4 on 2023-09-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salaire',
            field=models.FloatField(null=True),
        ),
    ]
